### ISSUE TITLE
google有错误提示，谢谢。

### ISSUE THREAD

**Issue by solife2020** [annProg/dztools#2]
![QQ截图20200520182753](https://user-images.githubusercontent.com/60801692/82436018-be4b5980-9ac7-11ea-952a-d206e610ef85.png)
![QQ截图20200520182743](https://user-images.githubusercontent.com/60801692/82436035-c1dee080-9ac7-11ea-8c2c-423b7e0fd5d0.png)

**Comment by annProg** [comment]
我这没报错。发一下报错的xml吧

**Comment by solife2020** [comment]
https://www.jzbar.net/sitemap/portal_sitemap.xml

**Comment by annProg** [comment]
你的 portal 和 group 似乎都没有内容，所以生成的 xml 是空的，可以在 google 里删除这 2 个 xml

**Comment by solife2020** [comment]
ok,THANKS
